name: jbntest1
favicon: null
layout_spectrum: 0.46116314828395844
typography_spectrum: 0.07752015674486756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2d2c'
    - '#00ffff'
    - '#0000ff'
    - '#8080ff'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.6219009559135884
  saturation: 0.8125
  rhythmicContrast: 0.19523658347316086
purpose: []
