name: jbntest1
favicon: null
layout_spectrum: 0.46116314828395844
typography_spectrum: 0.07752015674486756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.48406296828761697
  lightness: 0.6219009559135884
  saturation: 0.8222596442792565
  rhythmicContrast: 0.19523658347316086
purpose: []
